export const alimentos = [
  {
    id: 1,
    title: "Producto 1",
    price: 25000,
    stock: 4,
    description: "El producto es el 1",
    category: "asiatica",
    img: "https://res.cloudinary.com/dyt4eknl1/image/upload/v1677352509/cld-sample-5.jpg",
  },
  {
    id: 2,
    title: "Producto 2",
    price: 2000,
    stock: 6,
    description: "El producto es el 2",
    category: "venezolana",
    img: "https://res.cloudinary.com/dyt4eknl1/image/upload/v1677352508/cld-sample-3.jpg",
  },
  {
    id: 3,
    title: "Producto 3",
    price: 56000,
    stock: 9,
    description: "El producto es el 3",
    category: "peruana",
    img: "https://res.cloudinary.com/dyt4eknl1/image/upload/v1677352507/cld-sample.jpg",
  },
  {
    id: 4,
    title: "Producto 4",
    price: 67000,
    stock: 12,
    description: "El producto es el 4",
    category: "peruana",
    img: "https://res.cloudinary.com/dyt4eknl1/image/upload/v1677352509/cld-sample-4.jpg",
  },
  {
    id: 5,
    title: "Producto 5",
    price: 89000,
    stock: 2,
    description: "El producto es el 5",
    category: "venezolana",
    img: "https://res.cloudinary.com/dyt4eknl1/image/upload/v1677352508/cld-sample-3.jpg",
  },
  {
    id: 6,
    title: "Producto 6",
    price: 85000,
    stock: 8,
    description: "El producto es el 6",
    category: "asiatica",
    img: "https://res.cloudinary.com/dyt4eknl1/image/upload/v1677352509/cld-sample-5.jpg",
  },
  {
    id: 7,
    title: "Producto 7",
    price: 67000,
    stock: 5,
    description: "El producto es el 7",
    category: "venezolana",
    img: "https://res.cloudinary.com/dyt4eknl1/image/upload/v1677352509/cld-sample-4.jpg",
  },
];
